name: Release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  release:
    name: Build Release Binaries
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install GoReleaser
        run: |
          go install github.com/goreleaser/goreleaser/v2@latest

      - name: Release Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goreleaser release --clean